
const ANIMATION = {
	MOVE_RIGHT: "MOVE_RIGHT",
	MOVE_LEFT: "MOVE_LEFT",
	MOVE_UP: "MOVE_UP",
	MOVE_DOWN: "MOVE_DOWN",
	CARRY_RIGHT: "CARRY_RIGHT",
	CARRY_LEFT: "CARRY_LEFT",
	CARRY_UP: "CARRY_UP",
	CARRY_DOWN: "CARRY_DOWN",
	FIGHT_RIGHT: "FIGHT_RIGHT",
	FIGHT_LEFT: "FIGHT_LEFT",
	FIGHT_UP: "FIGHT_UP",
	FIGHT_DOWN: "FIGHT_DOWN"
};

const PEASANT_ACTIONS = {
	IDLE: "IDLE",
	MOVE: "MOVE",
	FIGHT: "FIGHT",
	BUILD: "BUILD",
	DRAG_GOLD: "DRAG_GOLD",
	CHOP_WOOD: "CHOP_WOOD",
	DRAG_WOOD: "DRAG_WOOD",
	
};

const BUILDING_STATE = {
    READY: "READY",
    BUILDING_SELF: "BUILDING_SELF",
    BUILDING_UNIT: "BUILDING_UNIT"
};

const TREE_FULL_HEALTH = 100;
const GOLD_MINE_GOLD_AMOUNT = 10000;
const treesIndexes = [75, 76, 77];
const TREE_STUB_INDEX = 74;

const GAME_EVENTS = {
	GOLD_MINED: "GOLD_MINED",
	WOOD_MINED: "WOOD_MINED",
	GOLD_MINE_EMPTY: "GOLD_MINE_EMPTY",
	TREE_EMPTY: "TREE_EMPTY",
	REQUEST_FOR_CLOSEST_TREE: "REQUEST_FOR_CLOSEST_TREE",
	PEASANT_BUILT: "PEASANT_BUILT"
}

const GAME_UNITS = {
	PEASANT: { name: "PEASANT", cost: { g: 100, w: 0 }, duration: 1000 },
	BARRACKS: { name: "BARRACKS", cost: { g: 300, w: 500 }, duration: 5000 },
	HOUSE: { name: "HOUSE", cost: { g: 0, w: 300 }, duration: 3000 },
	TOWN_CENTER: { name: "TOWN_CENTER", cost: {g: 1000, w: 1000}, duration: 10000 },
	GOLD_MINE: { name: "GOLD_MINE" }
}

export { ANIMATION, GAME_EVENTS, GAME_UNITS, PEASANT_ACTIONS, TREE_FULL_HEALTH, GOLD_MINE_GOLD_AMOUNT, TREE_STUB_INDEX, BUILDING_STATE }