name: Build, Test, Publish npm, Publish docs

on:
  push:
    branches:
      - github_actions  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code

      uses: actions/checkout@main
    - name: Install node modules
      run: |
        npm i
    - name: Install submodules
      run: |
        git submodule init
        git submodule update
    - name: Run build
      run: |
        npm run prepare-push
    - name: Temporarily save build
      uses: actions/upload-artifact@v4
      with:
          name: jsge-build-artifact
          path: ./
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Retrieve saved Artifact
        uses: actions/download-artifact@v2
        with:
          name: jsge-build-artifact
          path: ./
      - name: Regression test
        run: |
          npm run pu-r-test
  publish: 
    runs-on: ubuntu-latest
    steps:
      - name: Publish npm

        uses: ./.github/actions/publish_npm
      - name: Publish docs

        uses: ./.github/actions/publish_docs