name: Build, Test, Publish npm, Publish docs

on:
  push:
    branches:
      - github_actions  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code

      uses: actions/checkout@main
    - name: Install node modules
      run: |
        npm i
    - name: Install submodules
      run: |
        git submodule init
        git submodule update
    - name: Run build
      run: |
        npm run prepare-push
    - name: List files
      run: ls -la ./  # List files in the current directory
    - name: Temporarily save build
      uses: actions/upload-artifact@v4
      with:
          name: jsge_build_artifact
          path: ./
          if-no-files-found: warn
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve saved Artifact
        uses: actions/download-artifact@v4
        with:
          name: jsge_build_artifact
          path: ./
          if-no-artifact-found: warn
      - name: Update modules
        run: |
          npm update
      - name: Regression test
        run: |
          npm run pu-r-test
  publish: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Publish npm

        uses: ./.github/actions/publish_npm
      - name: Publish docs

        uses: ./.github/actions/publish_docs