name: Build, Test, Publish npm, Publish docs

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code

      uses: actions/checkout@main
    - name: Install node modules
      run: |
        npm i
    - name: Run build
      run: |
        npm run prepare-push
  regression:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Regression test
      run: |
        npm run pu-r-test
  publish_npm:
    runs-on: ubuntu-latest
    needs: regression

    steps:
    - name: Publish npm

      uses: ./.github/actions/publish_npm
    
  publish_docs:
    runs-on: ubuntu-latest
    needs: regression

    steps:
      - name: Publish docs

        uses: ./.github/actions/publish_docs