name: Test workflow. Build -> Regression test

on:
  push:
    branches:
      - test-workflow  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      current_version: ""
    steps:
    - name: Checkout code

      uses: actions/checkout@v4
    - name: Take version number
      run: |
        # Get the current version
        echo "current_version=$(grep '"version"' ./package.json | sed -E 's/.*"version": "([^"]+)".*/\1/')" >> $GITHUB_ENV
    - name: Fix version in docs
      run: | 
        echo "current version is ${{ env.current_version }}"
        
        sed -i "s/LATEST_VERSION/${{ env.current_version }}/" ./docs/templates/custom/tmpl/layout.tmpl
    - name: Fix version in examples
      run: | 
        sed -i 's/r=[^"].*"/r=${{ env.current_version }}"/' ./examples/index.html
    - name: Install node modules
      run: |
        npm i
    - name: Install submodules
      run: |
        git submodule init
        git submodule update
    - name: Run build
      run: |
        npm run prepare-push
    - name: Copy images
      run: |
        cp ./*.{png,gif} ./docs/build
    - name: Temporarily save build
      uses: actions/upload-artifact@v4
      with:
          name: jsge_build_artifact
          path: ./
          if-no-files-found: error
  regression_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve saved Artifact
        uses: actions/download-artifact@v4
        with:
          name: jsge_build_artifact
          path: ./
      - name: Fix modules
        run: |
          npm rebuild
      - name: Regression test
        run: |
          npm run pu-r-test